name: CI

on: [pull_request, workflow_dispatch]

env:
  GO_VERSION: "1.24"

jobs:
  main:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: ./.github/actions/build
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: "Ensure docs are up-to-date"
        if: ${{ github.event_name == 'pull_request' }}
        run: ./scripts/check-docs.sh
      
      - name: Lint
        run: make lint
      
      - name: Test
        run: make test
